import 'category.dart';
import 'package:flutter/material.dart';
import 'meal.dart';

const DUMMY_CATEGORIES = [
  Category(id: 'c1', title: 'Italian', colour: Colors.purple),
  Category(id: 'c2', title: 'Quick & easy', colour: Colors.red),
  Category(id: 'c3', title: 'Hamburger', colour: Colors.orange),
  Category(id: 'c4', title: 'German', colour: Colors.amber),
  Category(id: 'c5', title: 'Light & Lovely', colour: Colors.blue),
  Category(id: 'c6', title: 'Exotic', colour: Colors.green),
  Category(id: 'c7', title: 'Breakfast', colour: Colors.lightBlue),
  Category(id: 'c8', title: 'Asian', colour: Colors.lightGreen),
  Category(id: 'c9', title: 'French', colour: Colors.pink),
  Category(id: 'c10', title: 'Summer', colour: Colors.teal),
  Category(id: 'c11', title: 'Indian', colour: Colors.deepOrange),
];

const DUMMY_MEALS = [
  Meal(
      id: 'm1',
      categories: ['c1', 'c2'],
      title: 'Spaghetti with Tomato Sauce',
      affordability: 'Affordable',
      complexity: 'Simple',
      imageUrl:
          'https://stellar.co.uk/media/wysiwyg/Meatballs-Spaghetti-Cherry-Tomato-Sauce-Serving.jpg',
      ingredients: [
        '4 Tomatoes',
        '1 Tablespoon of Olive Oil',
        '1 Onion',
        '250g Spaghetti',
        'Spices (Salt, Pepper, Oregano)',
        'Cheese (optional)',
      ],
      steps: [
        'Cut the tomatoes and the onion into small pieces.',
        'Boil water in a large pot and cook the spaghetti.',
        'Heat olive oil in a pan and sauté the onion.',
        'Add tomatoes and spices, simmer for 10-15 minutes.',
        'Mix the cooked spaghetti with the sauce.',
        'Serve with cheese if desired.',
      ],
      isGlutenFree: false,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      duration: 20),
  Meal(
      id: 'm2',
      categories: ['c2'],
      title: 'Toast Hawaii',
      affordability: 'Affordable',
      complexity: 'Simple',
      imageUrl:
          'https://images.arla.com/recordid/0939FB3E-587A-46C4-9B5E06BF4EF267CC/picture.jpg?width=1200&height=630&mode=crop&format=jpg',
      ingredients: [
        '1 Slice White Bread',
        '1 Slice Ham',
        '1 Slice Pineapple',
        '1-2 Slices of Cheese',
        'Butter',
      ],
      steps: [
        'Butter one side of the white bread.',
        'Layer ham, pineapple, and cheese on the bread.',
        'Bake the toast for 10 minutes in the oven at 200°C.',
      ],
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false,
      duration: 10),
  Meal(
      id: 'm3',
      categories: ['c2', 'c3'],
      title: 'Classic Hamburger',
      affordability: 'Pricy',
      complexity: 'Simple',
      imageUrl:
          'https://rhubarbandcod.com/wp-content/uploads/2022/06/The-Classic-Cheeseburger-1-500x500.jpg',
      ingredients: [
        '300g Beef Patty',
        '1 Burger Bun',
        'Lettuce',
        'Tomato',
        'Onion',
        'Ketchup, Mustard',
      ],
      steps: [
        'Grill the beef patty to desired doneness.',
        'Toast the burger bun.',
        'Assemble the burger with patty, vegetables, and sauces.',
      ],
      isGlutenFree: false,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: false,
      duration: 45),
  Meal(
      id: 'm4',
      categories: ['c4'],
      title: 'Wiener Schnitzel',
      affordability: 'Luxurious',
      complexity: 'Challenging',
      imageUrl:
          'https://honest-food.net/wp-content/uploads/2012/12/wiener-schnitzel-horizontal.jpg',
      ingredients: [
        '8 Veal Cutlets',
        '4 Eggs',
        '200g Bread Crumbs',
        '100g Flour',
        'Butter',
        'Lemon Slices',
      ],
      steps: [
        'Tenderize the veal to 2–4mm thick.',
        'Dredge cutlets in flour, beaten eggs, and breadcrumbs.',
        'Fry in hot butter until golden brown.',
        'Serve with lemon slices.',
      ],
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false,
      duration: 60),
  Meal(
      id: 'm5',
      categories: ['c2', 'c5', 'c10'],
      title: 'Salad with Smoked Salmon',
      affordability: 'Luxurious',
      complexity: 'Simple',
      imageUrl:
          'https://i2.wp.com/www.downshiftology.com/wp-content/uploads/2018/08/Smoked-Salmon-Avocado-Arugula-Salad.jpg',
      ingredients: [
        'Arugula',
        'Lettuce',
        '200g Smoked Salmon',
        'Mustard Dressing',
        'Lemon Juice',
      ],
      steps: [
        'Wash and dry the salad greens.',
        'Arrange greens on a plate and top with smoked salmon.',
        'Drizzle with mustard dressing and lemon juice.',
      ],
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: false,
      duration: 15),
  Meal(
      id: 'm6',
      categories: ['c6', 'c10'],
      title: 'Delicious Orange Mousse',
      affordability: 'Affordable',
      complexity: 'Hard',
      imageUrl:
          'https://cdn.apartmenttherapy.info/image/upload/v1706023950/k/Photo/Recipes/2024-01-orange-creamsicle-mousse/orange-creamsicle-mousse-201_1.jpg',
      ingredients: [
        '4 Eggs',
        '100g Sugar',
        '300ml Orange Juice',
        'Gelatin',
        'Cream',
      ],
      steps: [
        'Separate eggs and beat yolks with sugar.',
        'Heat orange juice and mix with yolk mixture.',
        'Dissolve gelatin and mix into the mixture.',
        'Fold in whipped cream.',
        'Chill for at least 4 hours.',
      ],
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true,
      duration: 240),
  Meal(
      id: 'm7',
      categories: ['c7'],
      title: 'Pancakes',
      affordability: 'Affordable',
      complexity: 'Simple',
      imageUrl:
          'https://cdn2.egglandsbest.com/assets/images/recipes/_recipeImage/Fruity-Pancakes.jpg',
      ingredients: [
        '1 1/2 Cups Flour',
        '3 1/2 Tsp Baking Powder',
        '1 Tsp Salt',
        '1 Tbsp Sugar',
        '1 1/4 Cups Milk',
        '1 Egg',
        '3 Tbsp Butter, Melted',
      ],
      steps: [
        'Mix all dry ingredients.',
        'Add milk, egg, and melted butter. Mix until smooth.',
        'Cook pancakes on a hot griddle until golden brown on both sides.',
      ],
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true,
      duration: 20),
  Meal(
      id: 'm8',
      categories: ['c8'],
      title: 'Creamy Indian Chicken Curry',
      affordability: 'Pricy',
      complexity: 'Challenging',
      imageUrl:
          'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/foodcoworg-gmail.com/Easy_Creamy_Chicken_Curry.jpg',
      ingredients: [
        '500g Chicken Breast',
        '1 Onion',
        '2 Cloves Garlic',
        '1 Tbsp Ginger Paste',
        'Spices (Curry Powder, Garam Masala)',
        '200ml Cream',
        'Tomato Puree',
      ],
      steps: [
        'Sauté onion, garlic, and ginger in oil.',
        'Add chicken pieces and cook until brown.',
        'Add spices and tomato puree, cook for 10 minutes.',
        'Stir in cream and simmer until chicken is cooked through.',
      ],
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false,
      duration: 35),
  Meal(
      id: 'm9',
      categories: ['c9'],
      title: 'Chocolate Souffle',
      affordability: 'Affordable',
      complexity: 'Hard',
      imageUrl:
          'https://www.daysoftheyear.com/cdn-cgi/image/dpr=1%2Cf=auto%2Cfit=cover%2Ch=675%2Cq=85%2Csharpen=2%2Cw=1200/wp-content/uploads/chocolate-souffle-day-scaled.jpg',
      ingredients: [
        '2 Tbsp Butter',
        '2 Tbsp Flour',
        '120ml Milk',
        '100g Dark Chocolate',
        '2 Eggs',
        '2 Tbsp Sugar',
      ],
      steps: [
        'Preheat oven to 200°C.',
        'Make a roux with butter and flour, add milk to make a sauce.',
        'Melt chocolate into the sauce.',
        'Separate eggs, mix yolks into chocolate mixture.',
        'Whip egg whites with sugar until stiff, fold into chocolate.',
        'Bake in ramekins for 12–15 minutes.',
      ],
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true,
      duration: 45),
  Meal(
      id: 'm10',
      categories: ['c2', 'c5', 'c10'],
      title: 'Asparagus Salad with Cherry Tomatoes',
      affordability: 'Luxurious',
      complexity: 'Simple',
      imageUrl:
          'https://juliasalbum.com/wp-content/uploads/2021/09/asparagus-tomato-salad-with-burrata-cheese-1.jpg',
      ingredients: [
        'White and Green Asparagus',
        'Cherry Tomatoes',
        'Lettuce',
        'Olive Oil',
        'Balsamic Vinegar',
        'Salt, Pepper',
      ],
      steps: [
        'Boil asparagus until tender, then chop.',
        'Cut cherry tomatoes in half.',
        'Mix lettuce, tomatoes, and asparagus.',
        'Drizzle with olive oil and balsamic vinegar.',
        'Season with salt and pepper.',
      ],
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      duration: 30),
  Meal(
    id: 'm11',
    categories: ['c11'],
    title: 'Samosa',
    affordability: 'Affordable',
    complexity: 'Simple',
    imageUrl:
        'https://littlespicejar.com/wp-content/uploads/2022/04/My-Moms-Beef-Samosa-10-735x1103.jpg',
    ingredients: [
      '2 Cups All-Purpose Flour',
      '2 Potatoes (boiled & mashed)',
      '1/2 Cup Peas',
      'Spices (Turmeric, Garam Masala, Salt, Cumin)',
      'Oil for frying',
      'Water for dough',
    ],
    steps: [
      'Make dough with flour, salt, and water.',
      'Prepare stuffing with mashed potatoes, peas, and spices.',
      'Roll out dough, fill with stuffing, and shape into triangles.',
      'Deep fry until golden brown.',
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
    duration: 40,
  ),
  Meal(
    id: 'm12',
    categories: ['c11'],
    title: 'Thepla',
    affordability: 'Affordable',
    complexity: 'Simple',
    imageUrl:
        'https://rakskitchen.net/wp-content/uploads/2009/05/methi-thepla.jpg',
    ingredients: [
      '2 Cups Whole Wheat Flour',
      '1 Cup Fenugreek Leaves (Methi)',
      'Yogurt',
      'Spices (Turmeric, Red Chili Powder, Salt, Cumin)',
      'Oil',
    ],
    steps: [
      'Mix all ingredients to form dough.',
      'Roll into flat discs.',
      'Cook on a griddle with oil until golden spots appear.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
    duration: 30,
  ),
  Meal(
    id: 'm13',
    categories: ['c11'],
    title: 'Khaman',
    affordability: 'Affordable',
    complexity: 'Simple',
    imageUrl: 'https://pulses.org/images/com_yoorecipe/cropped-khaman.jpg',
    ingredients: [
      '1 Cup Gram Flour (Besan)',
      '1 Tbsp Lemon Juice',
      '1 Tsp ENO',
      'Spices (Salt, Turmeric, Green Chili)',
      'Oil, Mustard Seeds, Curry Leaves',
    ],
    steps: [
      'Make batter with besan, lemon juice, water, and ENO.',
      'Steam the batter in a greased tray.',
      'Temper with mustard seeds and curry leaves.',
      'Cut and serve.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
    duration: 25,
  ),
  Meal(
    id: 'm14',
    categories: ['c11'],
    title: 'Sev Usal',
    affordability: 'Affordable',
    complexity: 'Medium',
    imageUrl:
        'https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/52882cbef65887769c30a5ba29398c24',
    ingredients: [
      '1 Cup Dried Peas (soaked & boiled)',
      'Onion, Tomato, Ginger-Garlic Paste',
      'Spices (Usal Masala, Red Chili, Turmeric, Salt)',
      'Sev for topping',
      'Lemon, Coriander',
    ],
    steps: [
      'Prepare curry with peas, onions, tomatoes, and spices.',
      'Simmer until thickened.',
      'Top with sev, lemon juice, and coriander.',
    ],
    isGlutenFree: true,
    isLactoseFree: true,
    isVegan: true,
    isVegetarian: true,
    duration: 40,
  ),
  Meal(
    id: 'm15',
    categories: ['c11'],
    title: 'Paneer Butter Masala',
    affordability: 'Pricy',
    complexity: 'Hard',
    imageUrl:
        'https://www.ruchiskitchen.com/wp-content/uploads/2020/12/Paneer-butter-masala-recipe-3-480x270.jpg',
    ingredients: [
      '250g Paneer (cubed)',
      '2 Large Tomatoes (pureed)',
      '1 Onion (finely chopped)',
      '1 Tbsp Ginger-Garlic Paste',
      '2 Tbsp Butter',
      '1 Tbsp Oil',
      '100ml Fresh Cream',
      '1 Tsp Red Chili Powder',
      '1/2 Tsp Turmeric Powder',
      '1 Tsp Garam Masala',
      '1 Tsp Coriander Powder',
      '1 Tsp Sugar (optional)',
      'Salt to taste',
      'Fresh Coriander (for garnish)',
      'Kasuri Methi (crushed)',
    ],
    steps: [
      'Heat oil and 1 tbsp butter in a pan, sauté chopped onions until golden brown.',
      'Add ginger-garlic paste and cook for 1 minute until raw smell disappears.',
      'Add tomato puree and cook until oil separates.',
      'Add spices and salt, mix well.',
      'Add cream and sugar (if using), cook for 2-3 minutes on low flame.',
      'Add paneer cubes, cook for 5 minutes, stirring gently.',
      'Add remaining butter and crushed kasuri methi, mix and turn off heat.',
      'Garnish with coriander and serve hot with naan or rice.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
    duration: 30,
  ),
  Meal(
    id: 'm16',
    categories: ['c11'],
    title: 'Jalebi',
    affordability: 'Affordable',
    complexity: 'Hard',
    imageUrl:
        'https://static.toiimg.com/thumb/53099699.cms?imgsize=182393&width=800&height=800',
    ingredients: [
      '1 Cup All-Purpose Flour',
      '2 Tbsp Yogurt',
      'Sugar, Water (for syrup)',
      'Saffron, Cardamom',
      'Oil for frying',
    ],
    steps: [
      'Make batter with flour and yogurt, ferment for few hours.',
      'Prepare sugar syrup with saffron and cardamom.',
      'Pipe batter in hot oil in spiral shape, fry until golden.',
      'Dip in sugar syrup and serve.',
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: true,
    duration: 90,
  ),
];
